https://muistaa-cbz8p2bip9hejqcaezq9ue.streamlit.app/
[browser]
gatherUsageStats = false

[server]
headHTML = """
<!-- Open Graph / Facebook / Kakao -->
<meta property="og:type" content="website">
<meta property="og:title" content="Meidän ryhmä">
<meta property="og:description" content="Heidi opettajan B1-tasoa testaava hauska luokkatesti!">
<meta property="og:image" content="https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&auto=format&fit=crop">

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:title" content="Meidän ryhmä">
<meta property="twitter:description" content="Heidi opettajan B1-tasoa testaava hauska luokkatesti!">
<meta property="twitter:image" content="https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&auto=format&fit=crop">
"""
